# sms-notification-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-notification-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sms-notification-service
  template:
    metadata:
      labels:
        app: sms-notification-service
    spec:
      containers:
        - name: sms-notification-container
          image: akeelquamina/sms-notification-service:latest
          ports:
            - containerPort: 8080
