AWSTemplateFormatVersion: "2010-09-09"
Description: "EKS Cluster and NodeGroup Creation Stack"

Parameters:
  ClusterName:
    Type: String
    Description: "Name for the EKS Cluster"
    Default: "QuamTel"

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: "VPC ID where the EKS cluster will be created"

  PublicSubnet1:
    Type: AWS::EC2::Subnet::Id
    Description: "ID of the first public subnet"
  
  PublicSubnet2:
    Type: AWS::EC2::Subnet::Id
    Description: "ID of the second public subnet"

  PrivateSubnet1:
    Type: AWS::EC2::Subnet::Id
    Description: "ID of the first private subnet"

  PrivateSubnet2:
    Type: AWS::EC2::Subnet::Id
    Description: "ID of the second private subnet"

Resources:
  EKSClusterRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "EKSClusterRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "eks.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "EKSClusterPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "eks:DescribeCluster"
                Resource: "*"

  EKSNodegroupRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "EKSNodegroupRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "eks-nodegroup.amazonaws.com"
                - "ec2.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "EKSNodegroupPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "eks:ListNodegroups"
                  - "eks:CreateNodegroup"
                  - "eks:UpdateNodegroupConfig"
                  - "eks:DescribeNodegroup"
                  - "autoscaling:DescribeAutoScalingGroups"
                  - "autoscaling:DescribeLaunchConfigurations"
                Resource: "*"

  EKSCluster:
    Type: "AWS::EKS::Cluster"
    Properties:
      Name: !Ref ClusterName
      RoleArn: !GetAtt EKSClusterRole.Arn
      ResourcesVpcConfig:
        SubnetIds:
          - !Ref subnet-05932975c99209d15
          - !Ref subnet-0fcb93f5ba8981de3
          - !Ref subnet-0d65396d253631a43
          - !Ref subnet-075ad7dce3167e662
      Version: "1.27"

  NodeGroup:
    Type: "AWS::EKS::Nodegroup"
    DependsOn: EKSCluster
    Properties:
      ClusterName: !Ref ClusterName
      NodegroupName: "TAS"
      ScalingConfig:
        DesiredSize: 2
        MaxSize: 5
        MinSize: 1
      DiskSize: 20
      Subnets:
        - !Ref subnet-0d65396d253631a43
        - !Ref subnet-075ad7dce3167e662
      InstanceTypes:
        - t3.small
      NodeRole: !GetAtt EKSNodegroupRole.Arn
