---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: QuamTel
  region: us-east-2

nodeGroups:
  - name: TAS
    instanceType: t3.small
    desiredCapacity: 2
    maxSize: 3
    minSize: 1
    volumeSize: 20
    amiFamily: AmazonLinux2
    privateNetworking: true
    tags:
      nodegroup-type: worker
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
      withAddonPolicies:
        imageBuilder: true

vpc:
  clusterEndpoints:
    privateAccess: true
  cidr: 172.20.0.0/16
  id: vpc-0eb93143d766ebcf1
  subnets:
    private:
      us-east-2a:
        cidr: 172.20.128.0/19
        id: subnet-0c719827aa42b4461
      us-east-2b:
        cidr: 172.20.96.0/19
        id: subnet-04f7512d1213b94d9
    public:
      us-east-2a:
        cidr: 172.20.32.0/19
        id: subnet-0b267b7f2a11082ab
      us-east-2b:
        cidr: 172.20.64.0/19
        id: subnet-09b64bf069a48fbe7