---
apiVersion: eksctl.io/v1alpha5
eksclusterconfig:
  privateAccess: true
kind: ClusterConfig
metadata:
  name: QuamTel
nodeGroups:
- amiFamily: AmazonLinux2
  desiredCapacity: 2
  iam:
    attachPolicyARNs:
    - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
    - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
    - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
    withAddonPolicies:
      imageBuilder: true
  instanceType: t3.small
  maxSize: 3
  minSize: 1
  name: TAS
  tags:
    nodegroup-type: worker
  volumeSize: 20
resourcesvpcconfig:
  endpointPrivateAccess: true
vpc:
  cidr: 172.20.0.0/16
  id: vpc-0eb93143d766ebcf1
  subnets:
    private:
      us-east-2a:
        cidr: 172.20.128.0/19
        id: subnet-0c719827aa42b4461
      us-east-2b:
        cidr: 172.20.96.0/19
        id: subnet-04f7512d1213b94d9
    public:
      us-east-2a:
        cidr: 172.20.32.0/19
        id: subnet-0b267b7f2a11082ab
      us-east-2b:
        cidr: 172.20.64.0/19
        id: subnet-09b64bf069a48fbe7
