---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: QuamTel
  region: us-east-2

vpc:
  cidr: 172.20.0.0/16
  id: vpc-0dd90be52a719e88e
  subnets:
    private:
      us-east-2a: { id: subnet-0d65396d253631a43 }
      us-east-2b: { id: subnet-075ad7dce3167e662 }
    public:
      us-east-2a: { id: subnet-05932975c99209d15 }
      us-east-2b: { id: subnet-0fcb93f5ba8981de3 } 

nodeGroups:
  - name: TAS
    instanceType: t3.small
    desiredCapacity: 2
    maxSize: 3
    minSize: 1
    volumeSize: 20
    amiFamily: AmazonLinux2
    privateNetworking: true
    tags:
      nodegroup-type: worker
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
      withAddonPolicies:
        imageBuilder: true