apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: QuamTel
  region: us-east-2

vpc:
  cidr: 172.20.0.0/16
  subnets:
    publicSubnet1:
      cidr: 172.20.1.0/24
      availabilityZone: us-east-2a
      mapPublicIpOnLaunch: true

    publicSubnet2:
      cidr: 172.20.2.0/24
      availabilityZone: us-east-2b
      mapPublicIpOnLaunch: true

    privateSubnet1:
      cidr: 172.20.3.0/24
      availabilityZone: us-east-2a
      mapPublicIpOnLaunch: false

    privateSubnet2:
      cidr: 172.20.4.0/24
      availabilityZone: us-east-2b
      mapPublicIpOnLaunch: false

nodeGroups:
  - name: tas-nodegroup
    instanceType: t3.small
    minSize: 1
    maxSize: 2
    desiredCapacity: 2
    volumeSize: 20
    amiFamily: AmazonLinux2
    tags:
      nodegroup-type: "worker"
