apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: QuamTelco
  region: us-east-2

nodeGroups:
  - name: tas-nodegroup
    instanceType: t3.small
    minSize: 1
    maxSize: 2
    desiredCapacity: 2
    volumeSize: 20
    amiFamily: AmazonLinux2
    tags:
      nodegroup-type: "worker"
