apiVersion: eksctl.io/v1alpha5
availabilityZones:
- us-east-2a
- us-east-2b
kind: ClusterConfig
metadata:
  name: QuamTel
nodeGroups:
- amiFamily: AmazonLinux2
  desiredCapacity: 2
  instanceType: t3.small
  maxSize: 2
  minSize: 1
  name: tas-nodegroup
  tags:
    nodegroup-type: worker
  volumeSize: 20
vpc:
  cidr: 172.20.0.0/16
  id: vpc-0eb93143d766ebcf1
  subnets:
    private:
      us-east-2a: 172.20.64.0/19
      us-east-2b: 172.20.96.0/19
    public:
      us-east-2a: 172.20.0.0/19
      us-east-2b: 172.20.32.0/19