---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: QuamTel
  region: us-east-2

nodeGroups:
  - name: TAS
    instanceType: t3.small
    desiredCapacity: 2
    maxSize: 3
    minSize: 1
    volumeSize: 20
    amiFamily: AmazonLinux2
    tags:
      nodegroup-type: worker
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
      withAddonPolicies:
        imageBuilder: true

vpc:
  cidr: 172.20.0.0/16
  id: vpc-0dd90be52a719e88e
  subnets:
    zones:
      - us-east-2a
      - us-east-2b
