AWSTemplateFormatVersion: "2010-09-09"
Description: "EKS Cluster Creation Stack"

Resources:
  EKSNodegroupRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "EKSNodegroupRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "eks-nodegroup.amazonaws.com"
            Action: "sts:AssumeRole"

  EKSCluster:
    Type: "AWS::EKS::Cluster"
    Properties:
      Name: !Ref ClusterName
      RoleArn: arn:aws:iam::522424656191:role/aws-service-role/eks.amazonaws.com/AWSServiceRoleForAmazonEKS
      ResourcesVpcConfig:
        SubnetIds:
          - subnet-0d65396d253631a43
          - subnet-075ad7dce3167e662
          - subnet-05932975c99209d15
          - subnet-0fcb93f5ba8981de3
      Version: "1.26"

  NodeGroup:
    Type: "AWS::EKS::Nodegroup"
    DependsOn: EKSCluster
    Properties:
      ClusterName: !Ref ClusterName
      NodegroupName: "TAS"
      ScalingConfig:
        DesiredSize: 3
        MaxSize: 5
        MinSize: 1
      DiskSize: 20
      Subnets:
        - subnet-0d65396d253631a43
        - subnet-075ad7dce3167e662
        - subnet-05932975c99209d15
        - subnet-0fcb93f5ba8981de3
      InstanceTypes:
        - t3.small
      NodeRole: !GetAtt EKSNodegroupRole.Arn