AWSTemplateFormatVersion: "2010-09-09"
Description: "EKS Cluster Creation Stack"

Parameters:
  ClusterName:
    Type: String
    Description: "Name for the EKS Cluster"
    Default: "QuamTel"

Resources:
  EKSCluster:
    Type: "AWS::EKS::Cluster"
    Properties:
      Name: !Ref ClusterName
      RoleArn: arn:aws:iam::522424656191:role/aws-service-role/eks-nodegroup.amazonaws.com/AWSServiceRoleForAmazonEKSNodegroup
      ResourcesVpcConfig:
        SubnetIds:
          - subnet-0d65396d253631a43
          - subnet-075ad7dce3167e662
          - subnet-05932975c99209d15
          - subnet-0fcb93f5ba8981de3
      Version: "1.21"
