---
AWSTemplateFormatVersion: "2010-09-09"
Description: "EKS Cluster and NodeGroup Creation Stack"

Parameters:

  VpcBlock:
    Type: String
    Default: 172.20.0.0/16
    Description: The CIDR range for the VPC.

  PublicSubnet01Block:
    Type: String
    Default: 172.20.32.0/19
    Description: CidrBlock for public subnet 01

  PublicSubnet02Block:
    Type: String
    Default: 172.20.64.0/19
    Description: CidrBlock for public subnet 02

  PrivateSubnet01Block:
    Type: String
    Default: 172.20.128.0/19
    Description: CidrBlock for private subnet 01

  PrivateSubnet02Block:
    Type: String
    Default: 172.20.96.0/19
    Description: CidrBlock for private subnet 02

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Worker Network Configuration"
        Parameters:
          - VpcBlock
          - PublicSubnet01Block
          - PublicSubnet02Block
          - PrivateSubnet01Block
          - PrivateSubnet02Block
          
Resources:
  EKSClusterRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "EKSClusterRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "eks.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "EKSClusterPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "eks:DescribeCluster"
                Resource: "*"

  EKSNodegroupRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "EKSNodegroupRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "eks-nodegroup.amazonaws.com"
                - "ec2.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "EKSNodegroupPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "eks:ListNodegroups"
                  - "eks:CreateNodegroup"
                  - "eks:UpdateNodegroupConfig"
                  - "eks:DescribeNodegroup"
                  - "autoscaling:DescribeAutoScalingGroups"
                  - "autoscaling:DescribeLaunchConfigurations"
                Resource: "*"

  EKSCluster:
    Type: "AWS::EKS::Cluster"
    Properties:
      Name: !Ref ClusterName
      RoleArn: !GetAtt EKSClusterRole.Arn
      Version: "1.27"
      ResourcesVpcConfig:
        SubnetIds:
          - subnet-05932975c99209d15
          - subnet-0fcb93f5ba8981de3  
        EndpointPrivateAccess: true
        EndpointPublicAccess: true

  NodeGroup:
    Type: "AWS::EKS::Nodegroup"
    DependsOn: EKSCluster
    Properties:
      ClusterName: !Ref ClusterName
      NodegroupName: "TAS"
      ScalingConfig:
        DesiredSize: 3
        MaxSize: 5
        MinSize: 1
      DiskSize: 20
      Subnets:
        - subnet-0d65396d253631a43 
        - subnet-075ad7dce3167e662  
      InstanceTypes:
        - t3.small
      NodeRole: !GetAtt EKSNodegroupRole.Arn
