apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: QuamTel
  region: us-east-2

vpc:
  id: vpc-0eb93143d766ebcf1
  cidr: 172.20.0.0/16

availabilityZones: ["us-east-2a", "us-east-2b"]

nodeGroups:
  - name: tas-nodegroup
    instanceType: t3.small
    minSize: 1
    maxSize: 2
    desiredCapacity: 2
    volumeSize: 20
    amiFamily: AmazonLinux2
    tags:
      nodegroup-type: "worker"
    subnets:
      - subnet-0b267b7f2a11082ab  
      - subnet-0c719827aa42b4461
      - subnet-09b64bf069a48fbe7
      - subnet-04f7512d1213b94d9
