AWSTemplateFormatVersion: "2010-09-09"
Description: "EKS Cluster and NodeGroup Creation Stack"

Parameters:
  ClusterName:
    Type: String
    Description: "Name for the EKS Cluster"
    Default: "QuamTel"

Resources:
  EKSClusterRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "EKSClusterRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "eks.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "EKSClusterPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "eks:DescribeCluster"
                Resource: "*"

  EKSNodegroupRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "EKSNodegroupRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "eks-nodegroup.amazonaws.com"
                - "ec2.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "EKSNodegroupPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "eks:ListNodegroups"
                  - "eks:CreateNodegroup"
                  - "eks:UpdateNodegroupConfig"
                  - "eks:DescribeNodegroup"
                  - "autoscaling:DescribeAutoScalingGroups"
                  - "autoscaling:DescribeLaunchConfigurations"
                Resource: "*"

  EKSClusterSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupName: "EKSClusterSecurityGroup"
      VpcId: "vpc-0dd90be52a719e88e" 
      GroupDescription: "Security Group for EKS Cluster"
      SecurityGroupIngress:
        - CidrIp: "0.0.0.0/0"
          Description: "Allow all traffic to EKS control plane"
          IpProtocol: "-1"

  EKSCluster:
    Type: "AWS::EKS::Cluster"
    Properties:
      Name: !Ref ClusterName
      RoleArn: !GetAtt EKSClusterRole.Arn
      ResourcesVpcConfig:
        SubnetIds:
          - subnet-0d65396d253631a43
          - subnet-075ad7dce3167e662
        SecurityGroupIds:
          - !Ref EKSClusterSecurityGroup
      Version: "1.26"
  
  NodeGroup:
    Type: "AWS::EKS::Nodegroup"
    DependsOn: EKSCluster
    Properties:
      ClusterName: !Ref ClusterName
      NodegroupName: "TAS"
      ScalingConfig:
        DesiredSize: 3
        MaxSize: 5
        MinSize: 1
      DiskSize: 20
      Subnets:
        - subnet-05932975c99209d15
        - subnet-0fcb93f5ba8981de3
      InstanceTypes:
        - t3.small
      NodeRole: !GetAtt EKSNodegroupRole.Arn
      SecurityGroups:
        - !Ref EKSClusterSecurityGroup