apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: QuamTel
  region: us-east-2

vpc:
  id: vpc-0eb93143d766ebcf1
  cidr: 172.20.0.0/16
  subnets:
    public:
      us-east-2a: 172.20.32.0/19	
      us-east-2b: 172.20.64.0/19
    private:
      us-east-2a: 172.20.128.0/19
      us-east-2b: 172.20.96.0/19

availabilityZones: ["us-east-2a", "us-east-2b"]

nodeGroups:
  - name: tas-nodegroup
    instanceType: t3.small
    minSize: 1
    maxSize: 2
    desiredCapacity: 2
    volumeSize: 20
    amiFamily: AmazonLinux2
    tags:
      nodegroup-type: "worker"
