version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - echo "Executing pre-build commands"
      - echo Logging in to Docker Hub...
      - docker login
  build:
    commands:
      - echo "Building the Docker image for billing-service"
      - cd k8s-deployments
      - docker build -t akeelquamina/billing-service:v1 .
      - echo "Building the Docker image for sms-notification-service"
      - cd ../sms-notification-service
      - docker build -t akeelquamina/sms-notification-service:v1 .
      - echo "Building the Docker image for call-routing-service"
      - cd ../call-routing-service
      - docker build -t akeelquamina/call-routing-service:v1 .
  post_build:
    commands:
      - echo "Pushing Docker images to Docker Hub"
      - docker push akeelquamina/billing-service:v1
      - docker push akeelquamina/sms-notification-service:v1
      - docker push akeelquamina/call-routing-service:v1

artifacts:
  files: '**/*'
