pipeline {
    agent any

    environment {
        DOCKERHUB_USERNAME = credentials('DockerHub_Connection')
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Pull and Build Docker Images') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'DockerHub_Connection', usernameVariable: 'DOCKERHUB_USERNAME', passwordVariable: 'DOCKERHUB_PASSWORD')]) {
                
                        def services = ['billing-service', 'call-routing-service', 'sms-notification-service']

                        // Iterate over services
                        services.each { service ->
                            def imageTag = "v1"
                            def fullImageName = "akeelquamina/${service}:${imageTag}"

                            // Pull Docker image or ignore failure
                            sh "docker pull ${fullImageName} || true"

                            // Build and push Docker image
                            sh "docker buildx build -t ${fullImageName} ./Microservices_K8/${service}"
                            sh "docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}"
                            sh "docker push ${fullImageName}"
                        }
                    }
                }
            }
        }

        stage('Deploy to EKS') {
            steps {
                script {
                    def kubeconfig = readFile '/var/lib/jenkins/.kube/config' // Provide the path to your kubeconfig file

                    // Apply Kubernetes manifests for all three microservices
                    sh "kubectl --kubeconfig=$kubeconfig apply -f billing-service"
                    sh "kubectl --kubeconfig=$kubeconfig apply -f call-routing-service"
                    sh "kubectl --kubeconfig=$kubeconfig apply -f sms-notification-service"

                    // Wait for the deployment to complete for all three microservices
                    sh "kubectl --kubeconfig=$kubeconfig rollout status deployment billing-service-deployment"
                    sh "kubectl --kubeconfig=$kubeconfig rollout status deployment call-routing-service-deployment"
                    sh "kubectl --kubeconfig=$kubeconfig rollout status deployment sms-notification-service-deployment"
                }
            }
        }
    }
}
