pipeline {
    agent any

    environment {
        DOCKERHUB_USERNAME = credentials('DockerHub_Connection')
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Pull and Build Docker Images') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'DockerHub_Connection', usernameVariable: 'DOCKERHUB_USERNAME', passwordVariable: 'DOCKERHUB_PASSWORD')]) {
                        // Pull and build Docker images using Buildx
                        sh 'docker pull akeelquamina/billing-service:v1 || true'
                        sh 'docker buildx build -t akeelquamina/billing-service:v1 ./Microservices_K8/billing-service'
                        sh "docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}"
                        sh 'docker push akeelquamina/billing-service:v1'

                        sh 'docker pull akeelquamina/call-routing-service:v1 || true'
                        sh 'docker buildx build -t akeelquamina/call-routing-service:v1 ./Microservices_K8/call-routing-service'
                        sh "docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}"
                        sh 'docker push akeelquamina/call-routing-service:v1'

                        sh 'docker pull akeelquamina/sms-notification-service:v1 || true'
                        sh 'docker buildx build -t akeelquamina/sms-notification-service:v1 ./Microservices_K8/SMS-Notification-service'
                        sh "docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}"
                        sh 'docker push akeelquamina/sms-notification-service:v1'
                    }
                }
            }
        }

        stage('Deploy to EKS') {
            steps {
                script {
                    def kubeconfig = readFile('/home/ec2-user/.kube/config') // Provide the path to your kubeconfig file

                    // Apply Kubernetes manifests for all three microservices
                    sh "kubectl --kubeconfig=$kubeconfig apply -f billing-service/kubernetes/"
                    sh "kubectl --kubeconfig=$kubeconfig apply -f call-routing-service/kubernetes/"
                    sh "kubectl --kubeconfig=$kubeconfig apply -f sms-notification-service/kubernetes/"

                    // Wait for the deployment to complete for all three microservices
                    sh "kubectl --kubeconfig=$kubeconfig rollout status deployment billing-service-deployment"
                    sh "kubectl --kubeconfig=$kubeconfig rollout status deployment call-routing-service-deployment"
                    sh "kubectl --kubeconfig=$kubeconfig rollout status deployment sms-notification-service-deployment"
                }
            }
        }
    }
}
