apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-notification-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sms-notification-service
  template:
    metadata:
      labels:
        app: sms-notification-service
    spec:
      containers:
        - name: sms-notification-service-container
          image: akeelquamina/sms-notification-service:v1
          ports:
            - containerPort: 5000
          resources:
              requests:
                memory: "64Mi"
                cpu: "250m"
              limits:
                memory: "128Mi"
                cpu: "500m"